language: cpp
dist: focal
sudo: required

os:
  - linux
  - osx


# install build dependencies
before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    sudo apt-get install libwxgtk3.0-gtk3-dev libgtk2.0-dev libjpeg62-dev libgcrypt20-dev liblzo2-dev
    CMAKE_URL="http://www.cmake.org/files/v3.13/cmake-3.13.0-Linux-x86_64.tar.gz"
    mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/deps/cmake
    export PATH=${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install wxmac; brew reinstall libffi; brew upgrade cmake; fi


# Build steps
script:
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl; else cmake ..; fi
  - cmake --build .
  - cpack -V

# make builds available
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir package; cp *.dmg package/MultiVNC-prerelease.dmg; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir package; cp *.deb package/multivnc-prerelease.deb; fi

deploy:
  provider: surge
  login: dontmind@sdf.org
  token:
    secure: JK8jvuj7scuDGAdtbDPKlraao6NuloXSseWU8ZWJm+y/mvhlr14m1ITN8wTw3T/py1GDUpSI/Z9ilxv6tlpJSLKiqzx/1L5W8NGoPczfhMN/ugwvntyzGeGr56PF/bIUHDTNRwO5WH7JeGEyqqtEGr7Ms7dK3u0mmLS3xYr0izmsV0k2/0QN7Eo5Y6VS/RZyysVTM0oysrbJbMYxcH4KcarU3Hl11jzUyE/TWpGLJA8l7uCSDBBzjBnGtFlpmHRVuM5JQ7xvNd1m9fJS6pCMfP1zZakB5rpPbnZqUEWqWM/55Jo9zVUpn2o9jxNgcmD5mVKgKmjt4ZS/d6C7ORcP8OicsuLcnMYPBxmaMGEg9sJOZtiHPMPMII9H78vcX+7RYmtZ7FXUNWBtHWx07qhZAeeXtNro4yUJ8oKI7Pzf/uPZMhp2HNHL0dTfqxerksOzamtjwASzT4D8kCytDH7bKVbH5NRUvJn/hJBBAPEycPF6DnKidBxNfoGmOnAD40GMAxJDVDqaa4OELdohclPNrehDNLF42eQ7MFtAxw60I7voHTj/PgEnIstHzqQGaolV4y6I5+aQlGQwKfkT/K21wVxvqjD49oolv7M1qlvjMQ2EfmuQ+QEC3n9pe51XEYlJLQfJkRC5oSlHyF+6AKIjqw0vdBBYW39yfbJeilvEoOo=
  edge: true # opt in to dpl v2
  domain: multivnc-mac.surge.sh
  project: build/package
  on:
    condition: $TRAVIS_OS_NAME = osx

deploy:
  provider: surge
  login: dontmind@sdf.org
  token:
    secure: JK8jvuj7scuDGAdtbDPKlraao6NuloXSseWU8ZWJm+y/mvhlr14m1ITN8wTw3T/py1GDUpSI/Z9ilxv6tlpJSLKiqzx/1L5W8NGoPczfhMN/ugwvntyzGeGr56PF/bIUHDTNRwO5WH7JeGEyqqtEGr7Ms7dK3u0mmLS3xYr0izmsV0k2/0QN7Eo5Y6VS/RZyysVTM0oysrbJbMYxcH4KcarU3Hl11jzUyE/TWpGLJA8l7uCSDBBzjBnGtFlpmHRVuM5JQ7xvNd1m9fJS6pCMfP1zZakB5rpPbnZqUEWqWM/55Jo9zVUpn2o9jxNgcmD5mVKgKmjt4ZS/d6C7ORcP8OicsuLcnMYPBxmaMGEg9sJOZtiHPMPMII9H78vcX+7RYmtZ7FXUNWBtHWx07qhZAeeXtNro4yUJ8oKI7Pzf/uPZMhp2HNHL0dTfqxerksOzamtjwASzT4D8kCytDH7bKVbH5NRUvJn/hJBBAPEycPF6DnKidBxNfoGmOnAD40GMAxJDVDqaa4OELdohclPNrehDNLF42eQ7MFtAxw60I7voHTj/PgEnIstHzqQGaolV4y6I5+aQlGQwKfkT/K21wVxvqjD49oolv7M1qlvjMQ2EfmuQ+QEC3n9pe51XEYlJLQfJkRC5oSlHyF+6AKIjqw0vdBBYW39yfbJeilvEoOo=
  edge: true # opt in to dpl v2
  domain: multivnc-linux.surge.sh
  project: build/package
  on:
    condition: $TRAVIS_OS_NAME = linux
